server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: /home/isaac/Project/HydrantMap/server/configs
  application:
    name: hydrantmap-config
  profiles:
    active: native