spring:
  datasource:
    url: jdbc:h2:~/hydrantmap
    #username: sa
    #password: 
    #driver-class-name: com.h2.com
  jpa:
    show-sql: true
    
server:
  port: 8080
    
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: hydrant_p4ssw0rd
#    key-store-type: PKCS12
#    key-alias: tomcat
    
    
    
    